In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part-1. Data Preprocessing

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X=data.iloc[:,3:-1].values # drop columns Rownumber, CustomerId,Surname
y=data.iloc[:,-1].values   # Only the target variables

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding Categorical data

In [6]:
# Lable Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
# X[:,2] or data['Gender']
X[:,2]=le.fit_transform(X[:,2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## Building the ANN

In [12]:
# Initializing the ANN
ann=tf.keras.models.Sequential()    

In [13]:
# Adding the input layers and the first hidder layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))    

In [14]:
# Adding the Second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))  

In [15]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))  

## Part-3 Training the ANN

In [16]:
# Compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [17]:
# Trainig the ANN on the Training set
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 5s 4ms/step - loss: 0.5223 - accuracy: 0.7893
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.8061
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4381 - accuracy: 0.8073
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4255 - accuracy: 0.8106
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4175 - accuracy: 0.8146
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4110 - accuracy: 0.8196
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4036 - accuracy: 0.8255
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3946 - accuracy: 0.8316
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3843 - accuracy: 0.8395
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3747 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8675
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8650
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3319 - accuracy: 0.8660
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8652
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8633
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8658
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 0.8641
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3319 - accuracy: 0.8658
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8650
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 

## Predicting the result of a single Observation

In [18]:
# Geography:France
# Credit_Score:600
# Gender:Male
# Age:40 Year old
#Tenure:3 Years
# Balance:$60000
# Number of Products:2
# Does this customer have a credit card  ? Yes
# Is this customer an Active Member:Yes
# Estimated Salary:$50000
# so, Should we say goodbye to that customer?


print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 362ms/step
[[False]]


## Predicting the Test Set results

In [19]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1517   78]
 [ 198  207]]


0.862